# Specifies the build command and the directory where the built site is located.
[build]
  command = "npm run build"
  publish = "dist"

# Specifies the directory for serverless functions.
[functions]
  directory = "netlify/functions"

# Redirects all API calls from the frontend to our serverless functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback redirect for the single-page application (SPA).
# This ensures that all paths are routed to index.html for client-side routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
